export type UserType = 'buyer' | 'seller' | 'agent';

export interface OtpRecord {
  id: string;
  phone: string;      // E.164: +91XXXXXXXXXX
  code: string;       // 6-digit string
  userType: UserType; // scoped per app — same phone can have OTPs for different types
  expiresAt: string;  // ISO — 10 minutes from issue
  used: boolean;
}

export interface Session {
  id: string;
  userId: string;
  phone: string;
  userType: UserType;
  token: string;      // opaque to caller — generated by JwtPort
  issuedAt: string;
  expiresAt: string;  // ISO — 24 hours
  revoked: boolean;
}

export interface TokenPayload {
  sub: string;        // userId
  phone: string;
  userType: UserType;
  sessionId: string;
  iat: number;        // Unix seconds
  exp: number;        // Unix seconds
}
